name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - name: Switch to Linux docker mode
      run: |
        dir "C:\Program Files"
        "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon
    - name: Run mvn build
      run: mvn --batch-mode verify
